name: Push to kimbugp profile

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout builder repo
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout profile repo
        uses: actions/checkout@v2
        with:
          repository: kimbugp/kimbugp.github.io
          path: main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: |
          npm install
      - name: create gulp build
        run: |
          gulp
      - name: push to profile repo
        run: |
          bash entry.sh
        env:
          PROFILE_REPO_TOKEN: ${{ secrets.PROFILE_REPO_TOKEN }}
